Let ring know about the handler
If this isn't set, running `lein ring server` will cause
the following step of exceptions to occur:

Exception: java.lang.NullPointerException: null
  stacktrace.clj:15 ring.middleware.stacktrace/wrap-stacktrace-log[fn]
  ...

This is because it doesn't know what handler it needs to run! Duh!

Also, let users know how to run the ring server in the README